service: lambda-layer-service

frameworkVersion: '3'

useDotenv: true

provider:
  name: aws
  runtime: nodejs14.x
  region: eu-west-1
  profile: default
  environment:
    NODE_PATH: "./:/opt/node_modules"

functions:
  hello:
    handler: handler.handler
    events:
      - http:
          path: /
          method: get
          cors: true
    layers:
      - ${env:LAYER_ARN}
